#!/bin/bash 

if [ -z "$NSM_SESSION_NAME" ]; then
    echo 'must be run under nsm-proxy'
    exit 0
fi

if ! [ -a "$NSM_CLIENT_ID.midi" ]; then
    echo 'creating empty midi file'
    cp "$HOME/.local/share/seq24/blank.midi" "$NSM_CLIENT_ID.midi"
fi
exec seq24 "$NSM_CLIENT_ID.midi"
